# =============================================================================
# pwsh/packages/dev/00-Mise.ps1 — mirror of zsh/packages/dev/00-mise.zsh.
#
# Lifecycle package: installs mise (via scoop), activates PATH on shell
# start, and on `dotfiles install` runs `mise install --yes` against the
# shared manifest config/mise/config.toml.
#
# Load order: 00- prefix forces this to run before 01-MiseTools.ps1 so
# every downstream tool finds mise-managed binaries on PATH.
# =============================================================================

$script:DotfilesMiseLoaded = $false

function Test-MisePresent { return [bool](Get-Command mise -ErrorAction SilentlyContinue) }

# ── Install (idempotent — only runs when $env:DOTFILES_INSTALL is true) ─────
function Install-DotfilesMise {
    if (Test-MisePresent) { return $true }

    # Prefer scoop on Windows (matches docs/USECASES.md UC-3).
    if (Get-Command scoop -ErrorAction SilentlyContinue) {
        Write-DotfilesStep "Installing mise via scoop"
        scoop install mise
        if ($LASTEXITCODE -ne 0) {
            Write-DotfilesError "scoop install mise failed (exit $LASTEXITCODE)"
            return $false
        }
        return $true
    }

    # Universal fallback: upstream installer (POSIX shell required — we use
    # bash if available, else error out with guidance).
    if (Get-Command bash -ErrorAction SilentlyContinue) {
        Write-DotfilesStep "Installing mise via upstream installer (bash)"
        bash -c "curl -fsSL https://mise.run | sh"
        if ($LASTEXITCODE -ne 0) {
            Write-DotfilesError "mise installer failed (exit $LASTEXITCODE)"
            return $false
        }
        # Add ~/.local/bin to PATH for the rest of this session.
        $env:PATH = "$HOME\.local\bin;$env:PATH"
        return $true
    }

    Write-DotfilesError "Cannot install mise — scoop not found and bash not available"
    Write-DotfilesHint "Install scoop first: irm get.scoop.sh | iex"
    return $false
}

# ── Apply per-machine overrides (UC-7) ──────────────────────────────────────
function Sync-DotfilesMiseManifest {
    # DOTFILES_EXTRA: write a layered conf.d file so mise auto-merges extras.
    $confD = Join-Path ($env:XDG_CONFIG_HOME ?? "$env:USERPROFILE\.config") 'mise\conf.d'
    $extrasFile = Join-Path $confD 'dotfiles-extras.toml'
    if ($env:DOTFILES_EXTRA) {
        if (-not (Test-Path $confD)) { New-Item -ItemType Directory -Path $confD -Force | Out-Null }
        $lines = @(
            '# Auto-generated by dotfiles — managed by DOTFILES_EXTRA.'
            '# Edit via: dotfiles config set extra <comma-sep-tools>'
            '[tools]'
        )
        foreach ($t in $env:DOTFILES_EXTRA.Split(',')) {
            $t = $t.Trim()
            if ($t) { $lines += "$t = `"latest`"" }
        }
        $lines -join "`n" | Set-Content -Path $extrasFile -Encoding UTF8
    } elseif (Test-Path $extrasFile) {
        Remove-Item $extrasFile -Force
    }
}

# ── Post-install: materialize tools + apply excludes ─────────────────────────
function Invoke-DotfilesMiseInstall {
    if (-not (Test-MisePresent)) { return $false }

    Sync-DotfilesMiseManifest

    Write-DotfilesDebug 'mise: installing tools from manifest'
    mise install --yes 2>&1 | ForEach-Object { Write-DotfilesDebug "mise: $_" }
    if ($LASTEXITCODE -ne 0) {
        Write-DotfilesWarning "mise install reported failures — run 'mise doctor' for details"
    }

    # DOTFILES_EXCLUDE: uninstall any excluded tools.
    if ($env:DOTFILES_EXCLUDE) {
        foreach ($t in $env:DOTFILES_EXCLUDE.Split(',')) {
            $t = $t.Trim()
            if ($t) {
                Write-DotfilesDebug "mise: uninstalling excluded tool '$t'"
                mise uninstall $t --all 2>$null
            }
        }
    }
    return $true
}

# ── Doctor: provenance reporting (UC-12) ─────────────────────────────────────
function Test-DotfilesMiseHealth {
    $issues = 0
    if (-not (Test-MisePresent)) {
        Write-DotfilesResult 'mise' 'NOT FOUND'
        return 1
    }
    $ver = (mise --version 2>$null | Select-Object -First 1)
    Write-DotfilesResult 'mise' ($ver ?? 'installed')

    $current = mise current 2>$null
    if ($current) {
        Write-DotfilesDim 'active tools:'
        foreach ($line in $current -split "`r?`n") {
            if (-not $line) { continue }
            $parts = $line -split '\s+', 2
            $tool = $parts[0]; $toolVer = $parts[1]
            $bin = (Get-Command $tool -ErrorAction SilentlyContinue)
            if (-not $bin) {
                # Fallback: scan mise's install dir for any executable.
                $where = mise where $tool 2>$null
                if ($where -and (Test-Path $where)) {
                    $exe = Get-ChildItem -Path $where -Recurse -File -Filter '*.exe' -EA SilentlyContinue | Select-Object -First 1
                    if ($exe) { $bin = (Get-Command $exe.BaseName -ErrorAction SilentlyContinue) }
                }
            }
            if (-not $bin) {
                Write-DotfilesDim "  $tool $toolVer  [MISSING]"
                $issues++
                continue
            }
            $real = (Resolve-Path -LiteralPath $bin.Source -ErrorAction SilentlyContinue).Path
            # Ask mise directly where it installed this tool — works regardless
            # of the mise data dir (Linux ~/.local/share, Windows %LOCALAPPDATA%,
            # or user-customized MISE_DATA_DIR). Fall back to substring match
            # for cases where `mise where` fails.
            $miseWhere = (mise where $tool 2>$null | Select-Object -First 1)
            $src = if ($miseWhere -and $real -and $real.StartsWith($miseWhere, [StringComparison]::OrdinalIgnoreCase)) {
                'mise'
            } elseif ($real -match '[\\/]mise[\\/]installs[\\/]') {
                'mise'
            } elseif ($real -match '[\\/]scoop[\\/]apps[\\/]') {
                'scoop'
            } elseif ($real -match '^C:[\\/]Program Files[\\/]') {
                'system'
            } else {
                'unknown'
            }
            if ($src -eq 'mise') {
                Write-DotfilesDim "  $tool $toolVer  [mise]"
            } else {
                Write-DotfilesDim "  $tool $toolVer  [$src] ⚠ expected mise, got $($bin.Source)"
                $issues++
            }
        }
    }
    return $issues
}

# ── Shell-startup activation ─────────────────────────────────────────────────
function Initialize-DotfilesMise {
    if ($script:DotfilesMiseLoaded) { return }

    # On `dotfiles install` runs ($env:DOTFILES_INSTALL=true), ensure mise is
    # installed AND tools are materialized.
    if ($env:DOTFILES_INSTALL -eq 'true') {
        if (-not (Install-DotfilesMise)) { return }
    }

    if (Test-MisePresent) {
        # mise's pwsh integration is named differently across versions: newer
        # accepts `mise activate pwsh`; older only accepts `powershell`. Try
        # both, then sanity-check the output before eval'ing it — if mise
        # falls back to bash output, it contains `<<EOF` heredoc syntax that
        # PowerShell's parser rejects ("'<' operator is reserved").
        $activate = $null
        foreach ($shellName in @('pwsh','powershell')) {
            try { $activate = (& mise activate $shellName 2>$null | Out-String) }
            catch { Write-DotfilesDebug "mise activate $shellName threw: $_" }
            if ($activate -and $activate.Trim() -and $activate -notmatch '<<' -and $activate -notmatch '\bfunction\s+\w+\s*\(\)\s*\{') {
                break
            }
            $activate = $null
        }
        if ($activate) {
            try {
                Invoke-Expression $activate
            } catch {
                Write-DotfilesWarning "mise activate output failed to evaluate: $($_.Exception.Message)"
                Write-DotfilesHint  "Manually verify with: mise activate pwsh"
            }
        } else {
            Write-DotfilesWarning "mise activate didn't produce usable pwsh output — tools may not be on PATH"
            Write-DotfilesHint  "Check mise version (mise --version) and re-run; or activate manually"
        }

        if ($env:DOTFILES_INSTALL -eq 'true') {
            Invoke-DotfilesMiseInstall | Out-Null
        }
    }

    $script:DotfilesMiseLoaded = $true
}

# Fire init on shell startup (mirror of zsh-side pkg_init).
Initialize-DotfilesMise
