#!/usr/bin/env zsh

# Lives in core/ — every profile gets mise. The cumulative profile loader
# (core → server → develop) guarantees this file runs before any package
# in server/ or develop/, so by the time those `command -v <tool>` checks
# fire, mise's PATH is already active.

PKG_NAME="mise"
PKG_DESC="Polyglot tool & SDK version manager (replaces vfox + per-tool apt/brew)"

# Mise installs land in different prefixes depending on package manager:
#   apt    → /usr/bin/mise          (always on PATH)
#   brew   → /usr/local/bin or /opt/homebrew/bin or /home/linuxbrew/...
#   curl   → ~/.local/bin/mise      (appended by zsh/core/10-options.zsh)
#   cargo  → ~/.cargo/bin/mise
# The default `command -v` check fails when mise was installed somewhere
# `.zshrc`'s PATH setup doesn't cover (brew shellenv not loaded yet, etc.),
# producing a spurious "mise not installed" warning at every shell start.
# Probe known prefixes and prepend whichever has mise so the rest of init
# works without depending on PATH order.
_dotfiles_mise_check() {
    command -v mise &>/dev/null && return 0
    local _mise_bin _dir
    for _mise_bin in \
        "$HOME/.local/bin/mise" \
        "/usr/local/bin/mise" \
        "/opt/homebrew/bin/mise" \
        "/home/linuxbrew/.linuxbrew/bin/mise" \
        "$HOME/.cargo/bin/mise"
    do
        if [[ -x "$_mise_bin" ]]; then
            _dir="${_mise_bin%/*}"
            [[ ":$PATH:" != *":$_dir:"* ]] && export PATH="$_dir:$PATH"
            return 0
        fi
    done
    return 1
}
PKG_CHECK_FUNC="_dotfiles_mise_check"

# Tool manifest lives in config/mise/config.toml (symlinked to
# ~/.config/mise/config.toml). Edit that file to add/remove tools — runs
# transparently on the next `dotfiles install` via pkg_post_install.

pkg_install() {
    local os pkg_mgr
    os="$(dotfiles_os)"
    pkg_mgr="$(dotfiles_pkg_manager)"

    # All paths follow the official install guide: https://mise.jdx.dev/installing-mise.html
    if [[ "$os" == "macos" && "$pkg_mgr" == "brew" ]]; then
        brew install mise || return 1

    elif [[ "$pkg_mgr" == "apt" ]]; then
        # Official apt repo with signed keyring.
        sudo install -dm 755 /etc/apt/keyrings
        wget -qO - https://mise.jdx.dev/gpg-key.pub \
            | sudo gpg --dearmor -o /etc/apt/keyrings/mise-archive-keyring.gpg
        echo "deb [signed-by=/etc/apt/keyrings/mise-archive-keyring.gpg arch=amd64] https://mise.jdx.dev/deb stable main" \
            | sudo tee /etc/apt/sources.list.d/mise.list >/dev/null
        sudo apt-get update -qq && sudo apt-get install -y mise || return 1

    elif [[ "$pkg_mgr" == "dnf" || "$pkg_mgr" == "yum" ]]; then
        sudo tee /etc/yum.repos.d/mise.repo >/dev/null <<'EOF'
[mise]
name=Mise
baseurl=https://mise.jdx.dev/rpm
enabled=1
gpgcheck=1
gpgkey=https://mise.jdx.dev/gpg-key.pub
EOF
        sudo "$pkg_mgr" install -y mise || return 1

    elif [[ "$pkg_mgr" == "pacman" ]]; then
        sudo pacman -S --noconfirm mise || return 1

    else
        # Universal fallback: upstream curl|bash installer drops to ~/.local/bin.
        _dotfiles_log_info "mise: using upstream installer (pkg_mgr=$pkg_mgr)"
        curl -fsSL https://mise.run | sh || return 1
        # Make ~/.local/bin discoverable for the rest of this run.
        export PATH="$HOME/.local/bin:$PATH"
    fi
}

pkg_post_install() {
    if ! command -v mise &>/dev/null; then
        _dotfiles_log_warning "mise: binary not found after install"
        return 1
    fi

    # Apply DOTFILES_EXCLUDE / DOTFILES_EXTRA (UC-7): write the per-machine
    # overlay 99-machine.toml. mise auto-merges every *.toml in conf.d/, and
    # the `99-` prefix puts this file AFTER the shared shards in alphabetical
    # load order — so machine settings override shared declarations.
    #
    # EXCLUDE becomes [settings] disable_tools = [...]; EXTRA becomes
    # additional [tools] entries. Both empty → file removed (idempotent).
    local conf_d="${XDG_CONFIG_HOME:-$HOME/.config}/mise/conf.d"
    local overlay_file="$conf_d/99-machine.toml"
    if [[ -n "${DOTFILES_EXCLUDE:-}" || -n "${DOTFILES_EXTRA:-}" ]]; then
        mkdir -p "$conf_d"
        {
            print -- "# Auto-generated by dotfiles — managed by DOTFILES_EXCLUDE / DOTFILES_EXTRA."
            print -- "# Edit via: dotfiles config set exclude <comma-list>"
            print -- "#           dotfiles config set extra   <comma-list>"
            if [[ -n "${DOTFILES_EXCLUDE:-}" ]]; then
                print -- ""
                print -- "[settings]"
                local _quoted="" _t
                for _t in "${(s:,:)DOTFILES_EXCLUDE}"; do
                    [[ -z "$_t" ]] && continue
                    [[ -n "$_quoted" ]] && _quoted+=", "
                    _quoted+="\"$_t\""
                done
                print -- "disable_tools = [$_quoted]"
            fi
            if [[ -n "${DOTFILES_EXTRA:-}" ]]; then
                print -- ""
                print -- "[tools]"
                local _t
                for _t in "${(s:,:)DOTFILES_EXTRA}"; do
                    [[ -z "$_t" ]] && continue
                    printf '"%s" = "latest"\n' "$_t"
                done
            fi
        } > "$overlay_file"
        _dotfiles_log_debug "mise: wrote overlay $overlay_file"
    elif [[ -f "$overlay_file" ]]; then
        rm -f "$overlay_file"
        _dotfiles_log_debug "mise: removed empty overlay"
    fi

    # One-time cleanup for the pre-rename overlay path (dotfiles-extras.toml).
    # Safe to keep in perpetuity — no-op once everyone has migrated.
    [[ -f "$conf_d/dotfiles-extras.toml" ]] && rm -f "$conf_d/dotfiles-extras.toml"
    [[ -f "$conf_d/dotfiles.toml" ]] && rm -f "$conf_d/dotfiles.toml"

    # Materialize every tool from the merged manifest. Idempotent — mise
    # skips tools whose pinned version is already installed.
    _dotfiles_log_debug "mise: installing tools from manifest"
    if ! mise install --yes 2>&1 | while IFS= read -r line; do
        _dotfiles_log_debug "mise: $line"
    done; then
        _dotfiles_log_warning "mise install reported failures — run 'mise doctor' for details"
    fi

    # Apply DOTFILES_EXCLUDE (UC-7): uninstall any excluded tool. Silent
    # no-op if the tool isn't installed.
    if [[ -n "${DOTFILES_EXCLUDE:-}" ]]; then
        local _t
        for _t in "${(s:,:)DOTFILES_EXCLUDE}"; do
            [[ -z "$_t" ]] && continue
            _dotfiles_log_debug "mise: uninstalling excluded tool '$_t'"
            mise uninstall "$_t" --all 2>/dev/null || true
        done
    fi

    return 0
}

pkg_init() {
    [[ "${_DOTFILES_MISE_LOADED:-}" == "1" ]] && return 0

    # `mise activate zsh` registers a precmd hook that re-evaluates PATH
    # per-directory. Tools installed by mise show up in PATH immediately.
    command -v mise &>/dev/null && eval "$(mise activate zsh)"

    _DOTFILES_MISE_LOADED="1"   # NOT exported — must reset on `exec zsh`
}

pkg_doctor() {
    local issues=0

    if ! command -v mise &>/dev/null; then
        _dotfiles_log_result "mise" "NOT FOUND"
        ((issues++))
        return $issues
    fi

    local ver
    ver="$(mise --version 2>/dev/null | head -1)"
    _dotfiles_log_result "mise" "${ver:-installed}"

    local manifest="${XDG_CONFIG_HOME:-$HOME/.config}/mise/config.toml"
    if [[ -f "$manifest" ]]; then
        _dotfiles_log_dim "manifest: $manifest"
    else
        _dotfiles_log_dim "manifest: missing at $manifest"
        ((issues++))
    fi

    # Surface currently-installed tools + active versions + binary source.
    # UC-12 provenance: for each tool, report where the binary on PATH actually
    # came from. Catches "wrong tool wins on PATH" when an apt/brew copy beats
    # the mise shim. Source != mise increments the issue count.
    local current
    current="$(mise current 2>/dev/null || true)"
    if [[ -n "$current" ]]; then
        _dotfiles_log_dim "active tools:"
        # NOTE: don't redeclare `ver` here — outer scope already has `local ver`
        # from the mise --version capture, and `typeset name` on an already-set
        # parameter prints a "name='value'" declaration trace in zsh.
        local tool tool_ver bin_path real_path src mise_where _bin
        while IFS=$' \t' read -r tool tool_ver; do
            [[ -z "$tool" ]] && continue
            # Try the package name as the binary first (works for most tools).
            bin_path="$(command -v "$tool" 2>/dev/null || true)"
            # Fall back: install dirs vary by backend (some have `bin/`, others
            # like ripgrep's github release have a flat layout). Scan the whole
            # install tree for any executable, then verify it's on PATH.
            if [[ -z "$bin_path" ]]; then
                mise_where="$(mise where "$tool" 2>/dev/null || true)"
                if [[ -n "$mise_where" && -d "$mise_where" ]]; then
                    # zsh recursive glob: regular executable files (.x), nullglob (N)
                    for _bin in "$mise_where"/**/*(N.x); do
                        bin_path="$(command -v "${_bin:t}" 2>/dev/null || true)"
                        [[ -n "$bin_path" ]] && break
                    done
                fi
            fi
            if [[ -z "$bin_path" ]]; then
                _dotfiles_log_dim "  $tool $tool_ver  [MISSING]"
                ((issues++))
                continue
            fi
            # Resolve symlinks so we classify the real location, not the shim.
            real_path="$(readlink -f "$bin_path" 2>/dev/null || echo "$bin_path")"
            case "$real_path" in
                *"/.local/share/mise/installs/"*)                     src="mise" ;;
                /opt/homebrew/*|/usr/local/Cellar/*|/usr/local/opt/*) src="brew" ;;
                */.cargo/bin/*)                                       src="cargo" ;;
                */.bun/bin/*)                                         src="bun" ;;
                /usr/bin/*|/usr/sbin/*|/bin/*|/sbin/*)                src="system" ;;
                */.local/bin/*)                                       src="user" ;;
                *)                                                    src="unknown" ;;
            esac
            if [[ "$src" == "mise" ]]; then
                _dotfiles_log_dim "  $tool $tool_ver  [mise]"
            else
                _dotfiles_log_dim "  $tool $tool_ver  [${src}] ⚠ expected mise, got ${bin_path}"
                ((issues++))
            fi
        done <<< "$current"
    fi

    return $issues
}

pkg_clean() {
    local force="${DOTFILES_CLEAN_FORCE:-}"

    # mise download cache
    local cache_dir="${HOME}/.cache/mise"
    if [[ -d "$cache_dir" ]]; then
        _dotfiles_log_detail "mise: download cache at $cache_dir"
        if [[ "$force" == "--force" ]]; then
            rm -rf "$cache_dir" 2>/dev/null
            _dotfiles_log_detail "mise: removed download cache"
        fi
    fi

    # vfox leftover hint (inverse of the migration we just performed)
    local vfox_data="${HOME}/.version-fox"
    local vfox_config="${HOME}/.config/vfox"
    if [[ -d "$vfox_data" || -d "$vfox_config" ]]; then
        _dotfiles_log_detail "mise: vfox leftovers detected"
        [[ -d "$vfox_data" ]]   && _dotfiles_log_detail "  $vfox_data"
        [[ -d "$vfox_config" ]] && _dotfiles_log_detail "  $vfox_config"
        if [[ "$force" == "--force" ]]; then
            rm -rf "$vfox_data" "$vfox_config" 2>/dev/null
            _dotfiles_log_detail "mise: removed vfox leftover directories"
        else
            _dotfiles_log_detail "  (pass --force to remove)"
        fi
    fi

    return 0
}

pkg_uninstall() {
    local os pkg_mgr
    os="$(dotfiles_os)"
    pkg_mgr="$(dotfiles_pkg_manager)"

    # Remove all mise-managed tools first.
    if command -v mise &>/dev/null; then
        mise uninstall --all 2>/dev/null || true
    fi

    # Wipe mise runtime state. The config.toml symlink is handled by the
    # symlink sweep in uninstall_dotfiles — don't nuke the parent dir blindly.
    rm -rf "${HOME}/.local/share/mise" 2>/dev/null
    rm -rf "${HOME}/.cache/mise" 2>/dev/null

    local mise_config="${XDG_CONFIG_HOME:-$HOME/.config}/mise"
    local manifest_link="$mise_config/config.toml"
    if [[ -L "$manifest_link" ]]; then
        # Symlink sweep hasn't run yet — leave the link, clear siblings only.
        find "$mise_config" -mindepth 1 -not -name "config.toml" -delete 2>/dev/null || true
    else
        rm -rf "$mise_config" 2>/dev/null
    fi

    # Uninstall the binary itself — branches mirror pkg_install.
    if [[ "$os" == "macos" && "$pkg_mgr" == "brew" ]]; then
        if ! brew uninstall mise 2>/dev/null; then
            [[ -n "${_PKG_UNINSTALL_REPORT_FILE:-}" ]] && printf 'ERROR=%s\nREMAINING=%s\nRECOVERY=%s\n' \
                "brew uninstall mise failed" \
                "$(command -v mise 2>/dev/null || echo 'unknown')" \
                "run: brew uninstall mise" \
                > "$_PKG_UNINSTALL_REPORT_FILE"
            return 1
        fi

    elif [[ "$pkg_mgr" == "apt" ]]; then
        sudo apt-get remove -y mise 2>/dev/null || true
        sudo rm -f /etc/apt/sources.list.d/mise.list 2>/dev/null
        sudo rm -f /etc/apt/keyrings/mise-archive-keyring.gpg 2>/dev/null
        sudo apt-get update -qq 2>/dev/null || true

    elif [[ "$pkg_mgr" == "dnf" || "$pkg_mgr" == "yum" ]]; then
        sudo "$pkg_mgr" remove -y mise 2>/dev/null || true
        sudo rm -f /etc/yum.repos.d/mise.repo 2>/dev/null

    elif [[ "$pkg_mgr" == "pacman" ]]; then
        sudo pacman -Rs --noconfirm mise 2>/dev/null || true

    else
        # Curl-installer fallback path.
        local mise_bin
        mise_bin="$(command -v mise 2>/dev/null)"
        if [[ -n "$mise_bin" ]]; then
            if ! rm -f "$mise_bin" 2>/dev/null && ! sudo rm -f "$mise_bin" 2>/dev/null; then
                [[ -n "${_PKG_UNINSTALL_REPORT_FILE:-}" ]] && printf 'ERROR=%s\nREMAINING=%s\nRECOVERY=%s\n' \
                    "Failed to remove mise binary at $mise_bin" \
                    "$mise_bin" \
                    "run: sudo rm -f $mise_bin" \
                    > "$_PKG_UNINSTALL_REPORT_FILE"
                return 1
            fi
        fi
    fi

    return 0
}

init_package_template "$PKG_NAME"
